version: '3.1'

services:
  odoo:
    image: odoo:17
    container_name: ze_odoo_dev
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-data:/var/lib/odoo

  db:
    image: postgres:15
    container_name: ze_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  pg-data:
