name: Deploy Odoo ERP (Dev Branch)

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/odoo17
            git pull origin dev
            docker compose -f docker/dev/docker-compose.yml up -d --build
